---
config:
  look: handDrawn
  theme: base
  themeVariables:
    primaryColor: "#f8f9fa"       # Light gray for nodes
    primaryTextColor: "#333333"   # Dark gray text
    primaryBorderColor: "#cccccc" # Subtle borders
    lineColor: "#999999"          # Subtle line/edge color
    tertiaryColor: "#e8f5e9"      # Pastel green for highlight nodes
    secondaryColor: "#e8f5e9"     # Soft pastel blue for clusters
    fontFamily: "Arial, sans-serif"
    fontSize: "14px"
---
flowchart LR
    %% Flutter Application
    subgraph ZF[" "]
        direction LRdtz
            A[iOS App <br>**&lt;Flutter&gt;**]
            C[User Input Homepage <br>**&lt;Text Field&gt**] -->|URL| A
            D[User Input Question<br>**&lt;Microphone&gt**] -->|Audio| A
        end


    %% HTTP as Middle Layer
    B[HTTP]
    A <--> B

    subgraph ZB[" "]
        direction RL
            %% Python Backend Processes
            E[Backend<br>**&lt;Python FastAPI&gt;**]
            E -->|Audio| F[Audio Transcription<br>**&lt;Whisper&gt;**]
            E -->|URL| G[Homepage Parsing<br>**&lt;BeautifulSoup&gt;**]
            E -->|Question, Page| H[RAG Answer Generation<br>**&lt;llmware&gt;**]

            %% Backend Outputs
            F -->|Text| E
            G -->|Page| E
            H -->|Answer| E
        end

    B <--> E
